;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-change
        evil-complete-next
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-open-below
        evil-previous-line
        evil-visual-block
        evil-visual-char
        evil-window-down
        go-mode-insert-and-indent
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        evil-ex-search-next
        evil-first-non-blank
        evil-goto-first-line
        evil-mouse-drag-region
        evil-scroll-page-down
        evil-substitute
        keyboard-quit
        save-buffer-and-goes-to-normal-mode
        switch-to-previous-buffer
        ))
