;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        evil-append-line
        evil-backward-char
        evil-change
        evil-complete-next
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-escape-insert-state
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-open-below
        evil-previous-line
        evil-visual-block
        evil-visual-char
        go-mode-insert-and-indent
        ))

(setq mc/cmds-to-run-once
      '(
        clear-highlighted-search
        evil-ex
        evil-ex-search-next
        evil-window-down
        save-buffer-and-goes-to-normal-mode
        smex
        switch-to-previous-buffer
        ))
